version: '3'
services:
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: pulse_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pulse_development
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
